trigger:
  - main

pool:
  name: Default
  demands:
    - agent.os -equals myagent

steps:
- checkout: self

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'maven/target'
    ArtifactName: 'maven-build'
    publishLocation: 'Container'

